apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- query-deployment.yaml
- query-svc.yaml
images:
- name: ghcr.io/kyleee0522/springboot_crud_security_aop_query_feign
  newTag: "v1"
