apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-query
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend-query
  template:
    metadata:
      labels:
        app: backend-query
    spec:
      containers:
      - name: backend-query
        image: ghcr.io/kyleee0522/springboot_crud_security_aop_query_feign:v1
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
          - name: SERVER_PORT            
            value: "8082" 
        ports:
        - containerPort: 8080
